
--- Drop Tables
/*
DROP TABLE Batting;
DROP TABLE APPEARANCES;
DROP TABLE ALLSTARFULL;
DROP TABLE AWARDSMANAGERS;
DROP TABLE BATTINGPOST;
DROP TABLE FIELDING;
DROP TABLE FIELDINGPOST;
DROP TABLE FIELDINGOF;
DROP TABLE FIELDINGOFSPLIT;
DROP TABLE HALLOFFAME;
DROP TABLE HOMEGAMES;
DROP TABLE MANAGERS;
DROP TABLE MANAGERSHALF;
DROP TABLE PARKS;
DROP TABLE PEOPLE;
DROP TABLE PITCHING;
DROP TABLE PITCHINGPOST;
DROP TABLE SERIESPOST;
DROP TABLE TEAMS;
DROP TABLE TEAMSFRANCHISES;
DROP TABLE TEAMSHALF;
DROP PROCEDURE ContributionCount_sp;
DROP PROCEDURE DonatorLargeUnisex_sp;
DROP PROCEDURE VolunteersAndRecipientsByEvent_sp;
DROP PROCEDURE NumberOfEventsVolunteerd_sp;
DROP PROCEDURE AddDonator_sp;
DROP PROCEDURE IdentifiedRecipients_sp;
DROP VIEW DonatorReport_vw;
DROP VIEW VolunteerReport_vw;
*/
---Create Tables

CREATE TABLE    People (            
    PlayerID            VARCHAR(15)     PRIMARY KEY NOT NULL,
    BirithYear          INT                     NULL,
    BirthMonth          INT                     NULL,
    BirthDay            INT                     NULL,
    BirthCountry        VARCHAR(30)             NULL,
    BirthState          VARCHAR(30)             NULL,
    BirthCity           VARCHAR(30)             NULL,
    DeathYear           INT                     NULL,
    DeawthMonth         INT                     NULL,
    DeathDay            INT                     NULL,
    DeathCountry        VARCHAR(30)             NULL,
    DeathState          VARCHAR(30)             NULL,
    DeathCity           VARCHAR(30)             NULL,
    NameFirst           VARCHAR(30)             NULL,
    NameLast            VARCHAR(30)             NULL,
    NameGiven           VARCHAR(50)             NULL,
    Weight              INT                     NULL,
    Height              INT                     NULL,
    Baths               VARCHAR(5)              NULL,
    Throws              VARCHAR(5)              NULL,
    Debut               VARCHAR(15)             NULL,
    FinalGame           VARCHAR(15)             NULL,
    RetroID             VARCHAR(15)             NULL,
    bbrefID             VARCHAR(15)             NULL
);


CREATE TABLE    Batting (
    BatterEntryID       INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    Stint               INT             NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    Games               INT             NULL,
    AtBats              INT             NULL,
    Runs                INT             NULL,
    Hits                INT             NULL,
    Doubles             INT             NULL,
    Tripes              INT             NULL,
    HomeRuns            INT             NULL,
    RBI                 INT             NULL,
    StolenBases         INT             NULL,
    CaughtStealing      INT             NULL,
    BaseOnBalls         INT             NULL,
    StrikeOuts          INT             NULL,
    HitByPitch          INT             NULL,
    GIDP                INT             NULL,
    IBB                 INT             NULL,
    CONSTRAINT PK_Batting_BatterEntryID PRIMARY KEY(BatterEntryID),
    CONSTRAINT FK_Batting_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);

---Change Column 'Tripes' to 'Triples'
ALTER TABLE Batting
RENAME COLUMN Tripes TO Triples;

CREATE TABLE    BattingPost (
    BPEntryID           INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    RoundID             VARCHAR(5)      NOT NULL,
    TeamID              VARCHAR(5)      NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    Games               INT             NULL,
    AtBats              INT             NULL,
    Runs                INT             NULL,
    Hits                INT             NULL,
    Doubles             INT             NULL,
    Triples             INT             NULL,
    HomeRuns            INT             NULL,
    RBI                 INT             NULL,
    StolenBases         INT             NULL,
    CaughtStealing      INT             NULL,
    BaseOnBalls         INT             NULL,
    StrikeOuts          INT             NULL,
    HitByPitch          INT             NULL,
    GIDP                INT             NULL,
    IBB                 INT             NULL,
    SH                  INT             NULL,
    SF                  INT             NULL,
    CONSTRAINT FK_BattingPost_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    Fielding (
    FielderEntryID      INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    Stint               INT             NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    POS                 VARCHAR(5)      NULL,
    Games               INT             NULL,
    GamesStarted        INT             NULL,
    InnOuts             INT             NULL,
    PO                  INT             NULL,
    Assists             INT             NULL,
    ErrorsMade          INT             NULL,
    DoublePlays         INT             NULL,
    PB                  INT             NULL,
    WP                  INT             NULL,
    SB                  INT             NULL,
    CS_                 INT             NULL,
    ZR                  INT             NULL,
    CONSTRAINT FK_Fielding_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);

CREATE TABLE    FieldingPost (
    FPEntryID      INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    RoundID             VARCHAR(5)      NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    POS                 VARCHAR(5)      NULL,
    Games               INT             NULL,
    GamesStarted        INT             NULL,
    InnOuts             INT             NULL,
    PO                  INT             NULL,
    Assists             INT             NULL,
    ErrorsMade          INT             NULL,
    DoublePlays         INT             NULL,
    TriplePlays         INT             NULL,
    PB                  INT             NULL,
    WP                  INT             NULL,
    SB                  INT             NULL,
    CS_                 INT             NULL,
    CONSTRAINT FK_FieldingPost_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    FieldingOF (
    FOFEntryID          INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    Stint               INT             NULL,
    G_LF                INT             NULL,
    G_CF                INT             NULL,
    G_RF                INT             NULL,
    CONSTRAINT FK_FieldingOF_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);

CREATE TABLE    FieldingOFSplit (
    FOFSEntryID          INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    TeamID              VARCHAR(5)      NOT NULL,
    Stint               INT             NULL,
    LeagueID            VARCHAR(5)      NULL,
    POS                 VARCHAR(5)      NULL,
    Games               INT             NULL,
    GamesStarted        INT             NULL,
    InnOuts             INT             NULL,
    PO                  INT             NULL,
    Assists             INT             NULL,
    ErrorsMade          INT             NULL,
    DP_                 INT             NULL,
    PB                  INT             NULL,
    WP                  INT             NULL,
    SB                  INT             NULL,
    CS_                 INT             NULL,
    ZR                  INT             NULL,
    CONSTRAINT FK_FieldingOFSPlit_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    Pitching (
    PitcherEntryID      INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)    NOT NULL,
    YearID              INT             NOT NULL,
    Stint               INT              NOT NULL,
    TeamID              VARCHAR(10)      NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    Wins                INT             NULL,
    Losses              INT             NULL,
    Games               INT             NULL,
    GamesStarted        INT             NULL,
    CompleteGames       INT             NULL,
    SH                  INT             NULL,
    Saves               INT             NULL,
    IPouts              INT             NULL,
    Hits                INT             NULL,
    Runs                INT             NULL,
    EarnedRuns          INT             NULL,
    TotalRuns           INT             NULL,
    HomeRuns            INT             NULL,
    BaseOnBalls         INT             NULL,
    StrikeOuts          INT             NULL,
    BAOpp               VARCHAR(10)    NULL,
    ERA                 VARCHAR(10)    NULL,
    IBB                 INT             NULL,
    WP                  INT             NULL,
    HitByPitch          INT             NULL,
    BK                  INT             NULL,
    BFP                 INT             NULL,
    GF                  INT             NULL,
    SH2                 INT             NULL,
    SF                  INT             NULL,
    GIDP                INT             NULL,
    CONSTRAINT FK_Pitching_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);
---Change Column Names
ALTER TABLE Pitching
RENAME COLUMN SH TO ShutOuts; 

ALTER TABLE Pitching
RENAME COLUMN SH2 TO SH;

CREATE TABLE    PitchingPost (
    PPEntryID           INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    RoundID             VARCHAR(5)      NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    Wins                INT             NULL,
    Losses              INT             NULL,
    Games               INT             NULL,
    GamesStarted        INT             NULL,
    CompleteGames       INT             NULL,
    ShutOut             INT             NULL,
    Saves               INT             NULL,
    IPouts              INT             NULL,
    Hits                INT             NULL,
    Runs                INT             NULL,
    EarnedRuns          INT             NULL,
    TotalRuns           INT             NULL,
    HomeRuns            INT             NULL,
    BaseOnBalls         INT             NULL,
    StrikeOuts          INT             NULL,
    BAOpp               VARCHAR(10)    NULL,
    ERA                 VARCHAR(10)    NULL,
    IBB                 INT             NULL,
    WP                  INT             NULL,
    HitByPitch          INT             NULL,
    BK                  INT             NULL,
    BFP                 INT             NULL,
    GF                  INT             NULL,
    SH                  INT             NULL,
    SF                  INT             NULL,
    GIDP                INT             NULL,
    CONSTRAINT FK_PitchingPost_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    Managers (
    ManagerEntryID      INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    Inseaseon           INT             NULL,
    Games               INT             NULL,
    Wins                INT             NULL,
    Losses              INT             NULL,
    Rnk                 INT             NULL,
    PlyrMgr             VARCHAR(5)      NULL,
    CONSTRAINT FK_Managers_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);

ALTER TABLE Managers
    RENAME COLUMN Inseaseon TO Inseason;

CREATE TABLE    ManagersHalf (
    MHEntryID           INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    Inseason            INT             NULL,
    Half                INT             NULL,
    Games               INT             NULL,
    Wins                INT             NULL,
    Losses              INT             NULL,
    Rnk                 INT             NULL,
    CONSTRAINT FK_ManagersHalf_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);



CREATE TABLE    AwardsManagers (
    AMEntryID           INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    AwardID             VARCHAR(100)     NOT NULL,
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    Tie                 VARCHAR(5)      NULL,
    Notes               VARCHAR(200)    NULL,
    CONSTRAINT FK_AwardsManagers_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    AwardsShareManagers (
    AMSEntryID          INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    AwardID             VARCHAR(100)     NOT NULL,
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    PointsWon           INT             NULL,
    PointsMax           INT             NULL,
    VotesFirst          INT             NULL,
    CONSTRAINT FK_AwardsShareManagers_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);



CREATE TABLE    AwardsPlayers (
    APEntryID           INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    AwardID             VARCHAR(100)     NOT NULL,
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    Tie                 VARCHAR(5)      NULL,
    Notes               VARCHAR(200)    NULL,
    CONSTRAINT FK_AwardsPlayers_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    AwardsSharePlayers (
    APSEntryID          INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    AwardID             VARCHAR(100)    NOT NULL,
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    PointsWon           INT             NULL,
    PointsMax           INT             NULL,
    VotesFirst          INT             NULL,
    CONSTRAINT FK_AwardsSharePlayers_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    CollegePlaying (
    CPEntryID           INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    SchoolID            VARCHAR(50)     NOT NULL,
    YearID              INT             NOT NULL,
    CONSTRAINT FK_CollegePlaying_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    HallOfFame (
    HOFEntryID          INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    PlayerID            VARCHAR(10)     NOT NULL,
    YearID              INT             NOT NULL,
    VotedBy             VARCHAR(200)    NULL,
    Ballots             INT             NULL,
    VotesNeeded         INT             NULL,
    Votes               INT             NULL,
    Inducted            VARCHAR(3)      NULL,
    Category_           VARCHAR(20)     NULL,
    NeededNote          VARCHAR(100)    NULL,
    CONSTRAINT FK_HallOfFame_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    TeamsFranchises (
    FranchID            VARCHAR (10)    PRIMARY KEY NOT NULL,             
    FranchName          VARCHAR(100)     NULL,
    Active              VARCHAR (5)     NULL,
    NAassoc             VARCHAR(10)     NULL
);


CREATE TABLE    Teams (
    TeamEntryID        INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(10)      NOT NULL,
    TeamID              VARCHAR(10)     NOT NULL,
    TeamName            VARCHAR(50)     NULL,
    FranchID            VARCHAR(10)     NULL,    
    Park                VARCHAR(100)     NULL,
    Attendance           INT            NULL,
    DivisionID          VARCHAR(5)     NULL,
    Rnk                 INT             NULL, 
    Games               INT             NULL,
    GHome               INT             NULL,
    Wins                INT             NULL,
    Losses              INT             NULL,
    DivisionWin         VARCHAR(2)     NULL,
    WildCardWin         VARCHAR(2)     NULL,
    LeagueWin           VARCHAR(2)     NULL,
    WorldSeriesWin      VARCHAR(2)     NULL,
    Runs                INT             NULL,
    AtBats              INT             NULL,
    Hits                INT             NULL,
    Doubles             INT             NULL,
    Triples              INT             NULL,
    HomeRuns            INT             NULL,
    BaseOnBalls         INT             NULL,
    StrikeOuts          INT             NULL,
    StolenBases         INT             NULL,
    CaughtStealing      INT             NULL,
    HitByPitch          INT            NULL,
    SacFly              INT            NULL,
    RunsAllowed         INT            NULL,
    EarnedRuns          INT            NULL,
    ERA                 VARCHAR(10)    NULL,
    CompleteGames       INT            NULL,
    SH                  INT             NULL,
    Saves               INT             NULL,
    IPOuts              INT             NULL,
    HA                  INT             NULL,
    HRA                 INT             NULL,
    BBA                 INT             NULL,
    SOA                 INT             NULL,
    ErrM                INT             NULL,
    DP_                 INT             NULL,
    FieldingPercentage  DECIMAL(4,4)    NULL,
    BPF                 INT             NULL,
    PPF                 INT             NULL,
    TeamIDBR            VARCHAR(30)      NULL,
    TeamIDlahman45      VARCHAR(30)      NULL,
    TeamIDRetro         VARCHAR(30)      NULL,
    CONSTRAINT FK_Teams_FranchID FOREIGN KEY(FranchID) REFERENCES TeamsFranchises(FranchID)
);



CREATE TABLE    Appearances (
    AppearanceID        INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    TeamID              VARCHAR(5)     NOT NULL,
    PlayerID            VARCHAR(10)     NOT NULL,    
    G_all               INT            NULL,
    GS                  INT             NULL, 
    G_Batting           INT             NULL,
    G_Defense           INT             NULL,
    G_P                 INT             NULL,
    G_C                 INT             NULL,
    G_1B                INT             NULL,
    G_2B                INT             NULL,
    G_3B                INT             NULL,
    G_SS                INT             NULL,
    G_IF                INT             NULL,
    G_CF                INT             NULL,
    G_RF                INT             NULL,
    G_LF                INT             NULL,
    G_OF                INT             NULL,
    G_DH                INT             NULL,
    G_PH                INT            NULL,
    G_PR                INT            NULL,
    CONSTRAINT FK_Appearances_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    AllstarFull (
    ASFEntryID          INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,             
    YearID              INT             NOT NULL,
    LeagueID            VARCHAR(5)      NOT NULL,
    TeamID              VARCHAR(5)     NOT NULL,
    PlayerID            VARCHAR(10)     NOT NULL,
    GameID              VARCHAR(20)     NULL,
    GameNum             INT            NOT NULL,
    GP                  INT             NULL, 
    StartingPos         INT             NULL,
    CONSTRAINT FK_AllStarFull_PlayerID FOREIGN KEY(PlayerID) REFERENCES People(PlayerID)
);


CREATE TABLE    Parks (
    ParkID              VARCHAR(10)      PRIMARY KEY NOT NULL,
    ParkName            VARCHAR(100)     NOT NULL,
    ParkAlias           VARCHAR(100)     NULL,
    City                VARCHAR(50)      NULL,
    State_              VARCHAR(30)     NULL,
    Country             VARCHAR(10)      NULL
);


CREATE TABLE   HomeGames  (
    HomeSeasonID        INT GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1    PRIMARY KEY NOT NULL,
    ParkID              VARCHAR(10)     NOT NULL,
    YearID                INT             NOT NULL,
    LeagueID            VARCHAR(5)      NULL,
    TeamID              VARCHAR(5)      NOT NULL,
    SpanFirst           VARCHAR(25)     NULL,
    SpanLast            VARCHAR(25)     NULL,
    Games               INT             NULL,
    Openings            INT             NULL,
    Attendance          INT             NULL,
    CONSTRAINT FK_HomeGames_ParkID FOREIGN KEY(ParkID) REFERENCES Parks(ParkID)
);


